version: '3'

services:

  mongo:
    container_name: mongo
    hostname: mongo
    networks:
      workspace_net:
        ipv4_address: 172.16.230.2
    image: mongo
    restart: always
    environment:
      - DNSDOCK_ALIAS=mongo

  mongo_express:
    container_name: mongo_express
    hostname: mongo_express
    networks:
      workspace_net:
        ipv4_address: 172.16.230.3
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      - DNSDOCK_ALIAS=express

networks:
  workspace_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.230.0/24

