version: '3'

services:

  mongo:
    container_name: mongo
    hostname: mongo
    network_mode: "bridge"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017

  mongo_express:
    container_name: mongo_express
    hostname: mongo_express
    network_mode: "bridge"
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081
    links:
      - mongo


