version: '3'

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    command: --bind :9000 --no-auth --no-analytics --host unix:///var/run/docker.sock
    restart: always
    network_mode: "bridge"
    ports:
     - "9000:9000"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"

# New Entry Point: PC `192.168.1.101:2375`
