version: '3'

services:
  # https://github.com/DanielDent/docker-nginx-ssl-proxy
  ssl_proxy:
    container_name: ssl_proxy
    image: danieldent/nginx-ssl-proxy
    network_mode: "host"
    restart: "no"
    environment:
      UPSTREAM: localhost:8407
      SERVERNAME: pool.cx-pool.gq
      EXTRANAMES: wallet.cx-pool.gq
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert:/etc/letsencrypt"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
