version: '3'

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=pool.cx-pool.cf
      - VALIDATION=http
      - EMAIL=n8tb1t@gmail.com
      - STAGING=false
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  # https://github.com/DanielDent/docker-nginx-ssl-proxy
  ssl_proxy:
    container_name: ssl_proxy
    image: danieldent/nginx-ssl-proxy
    network_mode: "host"
    restart: "no"
    environment:
      UPSTREAM: localhost:17291
      SERVERNAME: pool.cx-pool.cf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert:/etc/letsencrypt"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
